# Generated by Django 4.2.3 on 2023-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("today", models.DateField()),
                ("max_temp", models.FloatField()),
                ("min_temp", models.FloatField()),
                ("avg_temp", models.FloatField()),
            ],
        ),
    ]
